### ISSUE TITLE
FastReport Designer Dialog Error

### ISSUE THREAD

**Issue by eliezeralmeida** [FastReports/FastReport#15]
### exception error:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at FastReport.Design.ReportTab.InitPages(Int32 index)
   at FastReport.Design.ReportTab.NewDialog()
   at FastReport.DevComponents.DotNetBar.BaseItem.RaiseClick(eEventSource source)
   at FastReport.DevComponents.DotNetBar.BaseItem.InternalMouseUp(MouseEventArgs objArg)
   at FastReport.DevComponents.DotNetBar.PopupItem.InternalMouseUp(MouseEventArgs objArg)
   at FastReport.DevComponents.DotNetBar.ButtonItem.InternalMouseUp(MouseEventArgs objArg)
   at FastReport.DevComponents.DotNetBar.BaseItem.InternalMouseUp(MouseEventArgs objArg)
   at FastReport.DevComponents.DotNetBar.GenericItemContainer.InternalMouseUp(MouseEventArgs objArg)
   at FastReport.DevComponents.DotNetBar.Bar.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Designer
    Assembly Version: 2018.4.7.0
    Win32 Version: 2018.4.7.0
    CodeBase: file:///C:/Users/Eliezer/Desktop/FastReport.Community/Designer.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
FastReport
    Assembly Version: 2018.4.7.0
    Win32 Version: 2018.4.7.0
    CodeBase: file:///C:/Users/Eliezer/Desktop/FastReport.Community/Designer.exe
----------------------------------------
FastReport.Bars
    Assembly Version: 1.0.0.0
    Win32 Version: 2018.4.7.0
    CodeBase: file:///C:/Users/Eliezer/Desktop/FastReport.Community/Designer.exe
----------------------------------------
FastReport.Editor
    Assembly Version: 1.0.0.0
    Win32 Version: 2018.4.7.0
    CodeBase: file:///C:/Users/Eliezer/Desktop/FastReport.Community/Designer.exe
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms.DataVisualization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.DataVisualization/v4.0_4.0.0.0__31bf3856ad364e35/System.Windows.Forms.DataVisualization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3160.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

### image:

![designer error](https://user-images.githubusercontent.com/2786448/47864760-2ef12f00-ddd9-11e8-9aab-239545edf648.png)

**Comment by fediachov** [comment]
Hi,

Thank for your message. This button should be disabled in Designer Community Edition. FastReport Open Source does not support dialogues in reports. We will fix this bug in next release of Designer.

**Comment by Detrav** [comment]
The button is disabled in [v2018.4.9](https://github.com/FastReports/FastReport/releases/tag/v2018.4.9)
