### ISSUE TITLE
Template contains image print exception

### ISSUE THREAD

**Issue by BlackPig-dev** [FastReports/FastReport#235]
Add PNG image directly in FRX, which is normal in version 2020.3.22, but abnormal in the latest version
`System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.PlatformNotSupportedException: System.Windows.Extensions types are not supported on this platform.
   at System.Drawing.ImageFormatConverter..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
   at System.ComponentModel.ReflectTypeDescriptionProvider.CreateInstance(Type objectType, Type callingType)
   at System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetConverter(Object instance)
   at System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultTypeDescriptor.System.ComponentModel.ICustomTypeDescriptor.GetConverter()
   at System.ComponentModel.TypeDescriptor.GetConverter(Object component)
   at FastReport.Utils.Converter.ToString(Object value)
   at FastReport.Utils.FRWriter.WriteValue(String name, Object value)
   at FastReport.PictureObject.Serialize(FRWriter writer)
   at FastReport.Utils.FRWriter.Write(IFRSerializable obj, Object diff)
   at FastReport.Preview.SourcePages.CloneObjects(Base source, Base parent)
   at FastReport.Preview.SourcePages.CloneObjects(Base source, Base parent)
   at FastReport.Preview.SourcePages.CloneObjects(Base source, Base parent)
   at FastReport.Preview.SourcePages.Add(ReportPage page)
   at FastReport.Preview.PreparedPages.AddSourcePage(ReportPage page)
   at FastReport.Engine.ReportEngine.InitializePages()
   at FastReport.Engine.ReportEngine.PrepareToFirstPass(Boolean append)
   at FastReport.Engine.ReportEngine.Run(Boolean runDialogs, Boolean append, Boolean resetDataState, ReportPage page)
   at FastReport.Engine.ReportEngine.Run(Boolean runDialogs, Boolean append, Boolean resetDataState)
   at FastReport.Report.Prepare(Boolean append)
   at FastReport.Report.Prepare()`

**Comment by BlackPig-dev** [comment]
`      Connection id "0HM4G7151P1KS", Request id "0HM4G7151P1KS:00000001": An unhandled exception was thrown by the application.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.PlatformNotSupportedException: System.Windows.Extensions types are not supported on this platform.
   at System.Drawing.ImageFormatConverter..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
   at System.ComponentModel.ReflectTypeDescriptionProvider.CreateInstance(Type objectType, Type callingType)
   at System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetConverter(Object instance)
   at System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultTypeDescriptor.System.ComponentModel.ICustomTypeDescriptor.GetConverter()
   at FastReport.Utils.Converter.ToString(Object value) in D:\GitHub\FastReport-master\FastReport.Base\Utils\Converter.cs:line 83
   at FastReport.Utils.FRWriter.WriteValue(String name, Object value) in D:\GitHub\FastReport-master\FastReport.Base\Utils\FRWriter.cs:line 320
   at FastReport.PictureObject.Serialize(FRWriter writer) in D:\GitHub\FastReport-master\FastReport.Base\PictureObject.cs:line 471
   at FastReport.Utils.FRWriter.Write(IFRSerializable obj, Object diff) in D:\GitHub\FastReport-master\FastReport.Base\Utils\FRWriter.cs:line 229
   at FastReport.Preview.SourcePages.CloneObjects(Base source, Base parent) in D:\GitHub\FastReport-master\FastReport.Base\Preview\SourcePages.cs:line 66
   at FastReport.Preview.SourcePages.CloneObjects(Base source, Base parent) in D:\GitHub\FastReport-master\FastReport.Base\Preview\SourcePages.cs:line 89
   at FastReport.Preview.SourcePages.CloneObjects(Base source, Base parent) in D:\GitHub\FastReport-master\FastReport.Base\Preview\SourcePages.cs:line 89
   at FastReport.Engine.ReportEngine.InitializePages() in D:\GitHub\FastReport-master\FastReport.Base\Engine\ReportEngine.cs:line 352
   at FastReport.Engine.ReportEngine.PrepareToFirstPass(Boolean append) in D:\GitHub\FastReport-master\FastReport.Base\Engine\ReportEngine.cs:line 369
   at FastReport.Engine.ReportEngine.Run(Boolean runDialogs, Boolean append, Boolean resetDataState, ReportPage page) in D:\GitHub\FastReport-master\FastReport.Base\Engine\ReportEngine.cs:line 436
   at FastReport.Engine.ReportEngine.Run(Boolean runDialogs, Boolean append, Boolean resetDataState) in D:\GitHub\FastReport-master\FastReport.Base\Engine\ReportEngine.cs:line 414
   at FastReport.Report.Prepare(Boolean append) in D:\GitHub\FastReport-master\FastReport.Base\Report.cs:line 2341`
