### ISSUE TITLE
when project  publish with  PublishSingleFile was  not working

### ISSUE THREAD

**Issue by jianliulin** [FastReports/FastReport#294]
dotnet publish ConsoleApp1.csproj -r win-x64 --self-contained=false /p:PublishSingleFile=true  

[ConsoleApp1.zip](https://github.com/FastReports/FastReport/files/6506523/ConsoleApp1.zip)

===========  Exception  ======================================

   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.OpenRead(String path)
   at Roslyn.Utilities.FileUtilities.OpenFileStream(String path)
   at Microsoft.CodeAnalysis.MetadataReference.CreateFromFile(String path, MetadataReferenceProperties properties, DocumentationProvider documentation)
   at FastReport.Code.CodeDom.Compiler.CodeDomProvider.GetReference(String refDll)
   at FastReport.Code.CodeDom.Compiler.CodeDomProvider.AddExtraAssemblies(StringCollection referencedAssemblies, List`1 references)
   at FastReport.Code.CSharp.CSharpCodeProvider.CompileAssemblyFromSource(CompilerParameters cp, String code)
   at FastReport.Code.AssemblyDescriptor.InternalCompile(CompilerParameters cp, CompilerResults& cr)
   at FastReport.Code.AssemblyDescriptor.InternalCompile()
   at FastReport.Code.AssemblyDescriptor.Compile()
   at FastReport.Report.Compile()
   at FastReport.Report.Prepare(Boolean append)
   at FastReport.Report.Prepare()
   at ConsoleApp1.Program.Main(String[] args)

===================Program.cs  ==============================================

```
using FastReport;
using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {

                var report = new FastReport.Report();
                report.Load("abc.frx");
                var ItemClass = new ItemClass()
                {
                    Material = new Material
                    {
                        MaterialName = "MaterialName"
                    },
                    MaterialName2 = "MaterialName2"

                };

                report.RegisterData(new List<ItemClass>() { ItemClass }, "table1", 2);
                using (MemoryStream stream = new MemoryStream())
                {
                    var export = new FastReport.Export.PdfSimple.PDFSimpleExport();

                    export.ShowProgress = false;
                    report.Prepare();
                    report.Export(export, stream);
                    stream.Flush();
                    report.Dispose();
                    stream.Position = 0;
                    var bytes = stream.ToArray();
                    System.IO.File.WriteAllBytes("export.pdf", bytes);
                }
            }
            catch (Exception ext)
            {
                Console.WriteLine(ext.StackTrace);
            }
        }


    }

    public class ItemClass
    {
        public Material Material { get; set; }
        public string MaterialName2 { get; set; }
    }


    public class Material
    {
        public string MaterialName { get; set; }
    }
}
```

====================== abc.frx ===============================================

```
<?xml version="1.0" encoding="utf-8"?>
<Report ScriptLanguage="CSharp" ReferencedAssemblies="" ReportInfo.Created="06/08/2020 08:20:14" ReportInfo.Modified="10/15/2020 10:41:20" ReportInfo.CreatorVersion="2020.3.4.0">
  <Dictionary>
    <BusinessObjectDataSource Name="table1" ReferenceName="table1" DataType="System.Collections.Generic.List`1[[ConsoleApp1.ItemClass, ConsoleApp1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]" Enabled="true">
      <Column Name="Material" DataType="ConsoleApp1.Material, ConsoleApp1,  Version=1.0.0.0, Culture=neutral, PublicKeyToken=null">
        <Column Name="MaterialNo" DataType="System.String"/>
        <Column Name="MaterialName" DataType="System.String"/>
      </Column>
      <Column Name="MaterialName2" DataType="System.String"/>
    </BusinessObjectDataSource>
  </Dictionary>
  <ReportPage PaperWidth="70" PaperHeight="40" LeftMargin="0" TopMargin="0" RightMargin="1" BottomMargin="2" FirstPageSource="15" OtherPagesSource="15" >
    <DataBand Width="260.82" Height="100.1">
      <TextObject Name="Text1" Left="3.45" Top="3.9" Width="236.25" Height="30.15"  Text="name：[table1.Material.MaterialName]"  />
    </DataBand>
  </ReportPage>
</Report>
```

**Comment by nm-1216** [comment]
2021.3 不存在这个问题

**Comment by nm-1216** [comment]
反射太繞了，開源源代碼 都不會改
