### ISSUE TITLE
System.OutOfMemoryException: Out of memory at System.Drawing.Graphics.Save()

### ISSUE THREAD

**Issue by purpleTurtle123** [FastReports/FastReport#327]
Hello, Im trying to create a PDF report and I keep stumbling upon this exception on my Centos 8 server (it works fluently on Windows) 
I noticed it only happens when the pdf report is +-2 pages in size, a one page report works fine.

I have also made a post on SuperUser: https://superuser.com/questions/1674769/asp-net-core-app-hosted-on-centos-8-throws-an-out-of-memory-exception-but-works?noredirect=1#comment2568586_1674769

Has anyone else encountered this issue and/or knows how to solve this?

Using the latest version of FR 

```
Sep 07 15:44:35 localhost.localdomain systemd[1]: Started fastreport.
Sep 07 15:44:35 localhost.localdomain fastreport[6907]: info: Microsoft.Hosting.Lifetime[0]
Sep 07 15:44:35 localhost.localdomain fastreport[6907]:       Now listening on: http://localhost:9999
Sep 07 15:44:35 localhost.localdomain fastreport[6907]: info: Microsoft.Hosting.Lifetime[0]
Sep 07 15:44:35 localhost.localdomain fastreport[6907]:       Application started. Press Ctrl+C to shut down.
Sep 07 15:44:35 localhost.localdomain fastreport[6907]: info: Microsoft.Hosting.Lifetime[0]
Sep 07 15:44:35 localhost.localdomain fastreport[6907]:       Hosting environment: Production
Sep 07 15:44:35 localhost.localdomain fastreport[6907]: info: Microsoft.Hosting.Lifetime[0]
Sep 07 15:44:35 localhost.localdomain fastreport[6907]:       Content root path: /var/www/fastreport
Sep 07 15:45:49 localhost.localdomain fastreport[6907]: fail: Microsoft.AspNetCore.Server.Kestrel[13]
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:       Connection id "0HMBI0N6CABKC", Request id "0HMBI0N6CABKC:00000002": An unhandled exception was thrown by the application.
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:       System.OutOfMemoryException: Out of memory.
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at System.Drawing.Graphics.Save()
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at FastReport.GdiGraphics.Save()
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at FastReport.TextObject.CalcSize()
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at FastReport.TextObject.InternalCalcHeight()
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at FastReport.TextObject.CalcHeight()
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at FastReport.Table.TableCellData.CalcHeight(Single width)
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at FastReport.Table.TableBase.CalcHeight()
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at FastReport.BandBase.CalcHeight()
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at FastReport.Engine.ReportEngine.PrepareBand(BandBase band, Boolean getData)
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at FastReport.Engine.ReportEngine.ShowBandToPreparedPages(BandBase band, Boolean getData)
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at FastReport.Engine.ReportEngine.ShowBand(BandBase band, Boolean getData)
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at FastReport.Engine.ReportEngine.ShowBand(BandBase band)
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at FastReport.Engine.ReportEngine.ShowDataBand(DataBand dataBand, Int32 rowCount)
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at FastReport.Engine.ReportEngine.RunDataBand(DataBand dataBand, Int32 rowCount, Boolean keepFirstRow, Boolean keepLastRow)
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at FastReport.Engine.ReportEngine.RunDataBand(DataBand dataBand)
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at FastReport.Engine.ReportEngine.RunBands(BandCollection bands)
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at FastReport.Engine.ReportEngine.RunReportPage(ReportPage page)
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at FastReport.Engine.ReportEngine.RunReportPages()
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at FastReport.Engine.ReportEngine.RunReportPages(ReportPage page)
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at FastReport.Engine.ReportEngine.Run(Boolean runDialogs, Boolean append, Boolean resetDataState, ReportPage page)
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at FastReport.Engine.ReportEngine.Run(Boolean runDialogs, Boolean append, Boolean resetDataState)
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at FastReport.Report.Prepare(Boolean append)
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at YinaPrintingService.Utilities.ProductieLijstTemplateUtility.GetProductieLijstRechts(List`1 dtos) in C:\Users\glenn\Source\Repos\fastreportprinting\YinaPrintingService\Utilities\ProductieLijstTemplateUtility.cs:line 271
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at YinaPrintingService.Factories.ProductieLijstRechtsFactory.GenerateReport(JArray array) in C:\Users\glenn\Source\Repos\fastreportprinting\YinaPrintingService\Factories\ProductieLijstRechtsFactory.cs:line 11
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at YinaPrintingService.Controllers.DocumentController.Index(JArray array, FastReportDocumentTemplate templateName, String printerName, OutputMode outMode) in C:\Users\glenn\Source\Repos\fastreportprinting\YinaPrintingService\Controllers\DocumentController.cs:line 48
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at lambda_method1(Closure , Object , Object[] )
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:       --- End of stack trace from previous location ---
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:       --- End of stack trace from previous location ---
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at FastReport.Web.FastReportMiddleware.Invoke(HttpContext httpContext)
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Sep 07 15:45:49 localhost.localdomain fastreport[6907]:          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by ATZ-FR** [comment]
Hello,
This is related to libgdiplus. Try to recompile it with pango support as described here -
https://www.fast-report.com/en/blog/show/Building-libgdiplus-library-from-source/

**Comment by ElBedeawi** [comment]
> Hello, This is related to libgdiplus. Try to recompile it with pango support as described here - https://www.fast-report.com/en/blog/show/Building-libgdiplus-library-from-source/

Thanks very much this worked for me and fixed the memory leaks, the api memory went down to ~200MB from 4-5 GB
