### ISSUE TITLE
SVG report isn't working

### ISSUE THREAD

**Issue by MrVitaly** [FastReports/FastReport#40]
## Versions
 - Fast Report:  Demos/FastReportCore.MVC.csproj fom the sources (as is) (master/Latest commit 664c4e9)
Reports\SVG.frx

## What happened
The following exception is occurring during opening `Report Objects/SVG` demo report:
``` 
An unhandled exception occurred while processing the request.
FileNotFoundException: Could not find file '...\FastReport\Demos\Core\FastReportCore.MVC\bin\Debug\netcoreapp2.0\Reports\SVG.frx'. 
```

### Steps to Reproduce
1. Run project `Demos/FastReportCore.MVC.csproj`;
2. Select `Report Objects/SVG` demo report;

### Expected behavior
The report `SVG.frx` should be shown.

### Screenshots
 - ![fastreportissue_3](https://user-images.githubusercontent.com/7189888/48966166-e6462380-efdc-11e8-947e-9496f310ccdb.png)
 - ![fastreportissue_4](https://user-images.githubusercontent.com/7189888/48966200-a03d8f80-efdd-11e8-8198-5d81ee700d9d.png)

### Logs
```
System.IO.FileNotFoundException: Could not find file 'H:\Master\Repository\FastReport\Demos\Core\FastReportCore.MVC\bin\Debug\netcoreapp2.0\Reports\SVG.frx'.
File name: 'H:\Master\Repository\FastReport\Demos\Core\FastReportCore.MVC\bin\Debug\netcoreapp2.0\Reports\SVG.frx'
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at FastReport.Report.Load(String fileName) in H:\Master\Repository\FastReport\FastReport.Base\Report.cs:line 1790
   at FastReportCore.MVC.Controllers.HomeController.Index(Nullable`1 report) in H:\Master\Repository\FastReport\Demos\Core\FastReportCore.MVC\Controllers\HomeController.cs:line 119
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

**Comment by fediachov** [comment]
Hi, 

Thanks for a detailed issue request. FastReport Open Source don't have the SVGObject, but you can use it in another edition https://github.com/FastReports/FastReport.Documentation/blob/master/COMPARISON.md

**Comment by fediachov** [comment]
We will definitely clean up our examples. Thanks for your support!

**Comment by fediachov** [comment]
We already have own SVGObject [based on SVG.NET](https://github.com/FastReports/SVG). We have plans to publish it in Open Source in near future.

**Comment by agiletools** [comment]
> We already have own SVGObject [based on SVG.NET](https://github.com/FastReports/SVG). We have plans to publish it in Open Source in near future.
Is it possible to use SVGObject in FastReport Open Source?
Please write the details.
