### ISSUE TITLE
Gauge report isn't working

### ISSUE THREAD

**Issue by MrVitaly** [FastReports/FastReport#41]
## Versions
 - Fast Report:  Demos/FastReportCore.MVC.csproj fom the sources (master/Latest commit 664c4e9 [as is])
 - Browsers: Google Chrome v. 70.0.3538.102 (64-bit), IE 11.407.17134.0, MS Edge 42.17134.1.0

## What happened
The following exception is occurring during opening `Report Objects/Gauge` demo report:
``` 
An unhandled exception occurred while processing the request.
CompilerException: (Function): Error CS0169: The field 'ReportScript.i' is never used
FastReport.Code.AssemblyDescriptor.InternalCompile() in AssemblyDescriptor.cs, line 454
```

### Steps to Reproduce
1. Run project `Demos/FastReportCore.MVC.csproj`;
2. Select `Report Objects/Gauge` demo report;

### Expected behavior
The report `SVG.frx` should be shown.

### Screenshots
 - ![fastreportissue_5](https://user-images.githubusercontent.com/7189888/48983802-877bc980-f104-11e8-8f09-91ecb87782cd.png)

 - ![fastreportissue_6](https://user-images.githubusercontent.com/7189888/48983806-8ea2d780-f104-11e8-8888-0d5cf8ff9c3c.png)

### Logs
```
FastReport.Utils.CompilerException: (Function): Error CS0169: The field 'ReportScript.i' is never used

   at FastReport.Code.AssemblyDescriptor.InternalCompile() in H:\Master\Repository\FastReport\FastReport.Base\Code\AssemblyDescriptor.cs:line 454
   at FastReport.Code.AssemblyDescriptor.Compile() in H:\Master\Repository\FastReport\FastReport.Base\Code\AssemblyDescriptor.cs:line 364
   at FastReport.Report.Compile() in H:\Master\Repository\FastReport\FastReport.Base\Report.cs:line 1150
   at FastReport.Report.Prepare(Boolean append) in H:\Master\Repository\FastReport\FastReport.Base\Report.cs:line 2169
   at FastReport.Report.Prepare() in H:\Master\Repository\FastReport\FastReport.Base\Report.cs:line 2129
   at FastReportCore.MVC.Controllers.HomeController.Index(Nullable`1 report) in H:\Master\Repository\FastReport\Demos\Core\FastReportCore.MVC\Controllers\HomeController.cs:line 121
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

**Comment by Detrav** [comment]
Hello, @MrVitaly, thank you for issue, our Roslyn wrapper decided that a warning should be raised as an error, I will fix it.
