### ISSUE TITLE
Problems using the web interface in the paid version

### ISSUE THREAD

**Issue by chenryhabana205** [FastReports/FastReport#427]
- Trying to use a dialog, the application throws an error.
System.NullReferenceException: Object reference not set to an instance of an object.
   at FastReport.Web.Dialog.GetControlFont(Font font)
   at FastReport.Web.Dialog.GetStandardStyle(DialogControl control)
   at FastReport.Web.Dialog.GetButtonStyle(ButtonControl control)
   at FastReport.Web.Dialog.GetButtonHtml(ButtonControl control)
   at FastReport.Web.Dialog.GetComponentHtml(StringBuilder sb, DialogComponentCollection collection)
   at FastReport.Web.Dialog.GetDialogHtml(StringBuilder sb, DialogPage dialog)
   at FastReport.Web.Dialog.ProcessDialogs(StringBuilder sb)
   at FastReport.Web.WebReport.ReportBody()
   at FastReport.Web.WebReport.template_body(Boolean renderBody)
   at FastReport.Web.WebReport.template_render(Boolean renderBody)
   at FastReport.Web.WebReport.Render(Boolean renderBody)
   at FastReport.Web.Controllers.ReportController.<.ctor>b__0_0()
   at FastReport.Web.Controllers.BaseController.OnRequest(HttpContext httpContext)
   at FastReport.Web.FastReportMiddleware.RequestFastReportController(HttpContext httpContext)
   at FastReport.Web.FastReportMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

- When installing the POS.exe file, designing a report in the tool that comes by default and then uploading that report to the version of the web designer, this report does not work.
In the tools the tables are named "NAME of the Table" and in the web version they are called "Schema.Name of the table"

**Comment by MaratAlaev** [comment]
Hello!

This problem is not reproduced at the moment 

Best regards 
Marat
