### ISSUE TITLE
Question: How to RegisterData CSV DataSource and connect the data for use with dynamically built TableObject?

### ISSUE THREAD

**Issue by githubfanster** [FastReports/FastReport#49]
this is a follow up to https://github.com/FastReports/FastReport/issues/47.
now that i have a report template that's working in the community designer, i'd like to load that template into my web app.
if i run the attached project zip, i get the following exception and stack trace. 

StackTrace

FastReport.Utils.DataTableException: products: Table is not connected to the data. Register the data using Report.RegisterData method.
   at FastReport.Code.AssemblyDescriptor.InvokeEvent(String name, Object[] parms)
   at FastReport.BandBase.SaveState()
   at FastReport.Engine.ReportEngine.ShowBandToPreparedPages(BandBase band, Boolean getData)
   at FastReport.Engine.ReportEngine.ShowBand(BandBase band, Boolean getData)
   at FastReport.Engine.ReportEngine.RunDataBand(DataBand dataBand, Int32 rowCount, Boolean keepFirstRow, Boolean keepLastRow)
   at FastReport.Engine.ReportEngine.RunDataBand(DataBand dataBand)
   at FastReport.Engine.ReportEngine.RunBands(BandCollection bands)
   at FastReport.Engine.ReportEngine.RunReportPage(ReportPage page)
   at FastReport.Engine.ReportEngine.RunReportPages()
   at FastReport.Engine.ReportEngine.RunReportPages(ReportPage page)
   at FastReport.Engine.ReportEngine.Run(Boolean runDialogs, Boolean append, Boolean resetDataState, ReportPage page)
   at FastReport.Report.Prepare(Boolean append)
   at FastReport.Web.Controllers.ReportController.<.ctor>b__0_0()
   at FastReport.Web.Controllers.BaseController.OnRequest(HttpContext httpContext)
   at FastReport.Web.FastReportMiddleware.RequestFastReportController(HttpContext httpContext)
   at FastReport.Web.FastReportMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

The demo seems to only have examples of how to Load xml data and RegisterData for xml-based DataSets.

How may I RegisterData a CSV DataSource and connect the data for use with my TableObject?
[Web22Demo.zip](https://github.com/FastReports/FastReport/files/2662564/Web22Demo.zip)

Thanks for any tips or help!

**Comment by Detrav** [comment]
Hi, check the path to the CSV file in ConnectionString, maybe you used the absolute path

**Comment by Detrav** [comment]
I’m closing this issue because it has been inactive for a few weeks. This probably means that it is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/FastReports/FastReport/releases).

Thank you!
