### ISSUE TITLE
Null Ref Exception in Designer while create new datasource->choose tables

### ISSUE THREAD

**Issue by skygunner** [FastReports/FastReport#544]
**Describe the bug**
Designer CE 2023.1.0 Null Ref Exception in Designer while create new datasource->choose tables

**To Reproduce**
Designer CE 2023.1.0
standard report wizard
create new datasource
choose tables
click check all -> null ref 

**Expected behavior**

**Stacktrace**

```CSharp
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at FastReport.Forms.QueryWizardForm.set_VisiblePanelIndex(Int32 value)
   at FastReport.Forms.DataWizardForm.tvTables_AfterCheck(Object sender, TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.OnAfterCheck(TreeViewEventArgs e)
   at FastReport.Forms.DataWizardForm.cbxCheckAll_CheckedChanged(Object sender, EventArgs e)
   at System.Windows.Forms.CheckBox.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
   at System.Windows.Forms.CheckBox.OnClick(EventArgs e)
   at System.Windows.Forms.CheckBox.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies 
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9105.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll

Designer
    Assembly Version: 2023.1.0.0
    Win32 Version: 2023.1.0.0
    CodeBase: file:///E:/Projects/FastReport.Community.2023.1.0/Designer.exe

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9075.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9065.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9115.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

FastReport
    Assembly Version: 2023.1.0.0
    Win32 Version: 2023.1.0.0
    CodeBase: file:///E:/Projects/FastReport.Community.2023.1.0/Designer.exe

FastReport.Bars
    Assembly Version: 2023.1.0.0
    Win32 Version: 2023.1.0.0
    CodeBase: file:///E:/Projects/FastReport.Community.2023.1.0/Designer.exe

FastReport.Editor
    Assembly Version: 2023.1.0.0
    Win32 Version: 2023.1.0.0
    CodeBase: file:///E:/Projects/FastReport.Community.2023.1.0/Designer.exe

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

FastReport.Compat
    Assembly Version: 2022.3.2.0
    Win32 Version: 2022.3.2.0
    CodeBase: file:///E:/Projects/FastReport.Community.2023.1.0/FastReport.Compat.DLL

FastReport.DataVisualization
    Assembly Version: 2022.3.2.0
    Win32 Version: 2022.3.2.0
    CodeBase: file:///E:/Projects/FastReport.Community.2023.1.0/FastReport.DataVisualization.DLL

System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9110.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll

FastReport.Data.Couchbase
    Assembly Version: 2023.1.0.0
    Win32 Version: 2023.1.0.0
    CodeBase: file:///E:/Projects/FastReport.Community.2023.1.0/Designer.exe

FastReport.Data.Json
    Assembly Version: 2023.1.0.0
    Win32 Version: 2023.1.0.0
    CodeBase: file:///E:/Projects/FastReport.Community.2023.1.0/FastReport.Data.Json.DLL

FastReport.Data.Json
    Assembly Version: 2023.1.0.0
    Win32 Version: 2023.1.0.0
    CodeBase: file:///E:/Projects/FastReport.Community.2023.1.0/Designer.exe

Newtonsoft.Json
    Assembly Version: 11.0.0.0
    Win32 Version: 11.0.2.21924
    CodeBase: file:///E:/Projects/FastReport.Community.2023.1.0/Newtonsoft.Json.DLL

FastReport.Data.MongoDB
    Assembly Version: 2023.1.0.0
    Win32 Version: 2023.1.0.0
    CodeBase: file:///E:/Projects/FastReport.Community.2023.1.0/Designer.exe

FastReport.Data.MySql
    Assembly Version: 2023.1.0.0
    Win32 Version: 2023.1.0.0
    CodeBase: file:///E:/Projects/FastReport.Community.2023.1.0/Designer.exe

FastReport.Data.OracleODPCore
    Assembly Version: 2023.1.0.0
    Win32 Version: 2023.1.0.0
    CodeBase: file:///E:/Projects/FastReport.Community.2023.1.0/Designer.exe

FastReport.Data.Postgres
    Assembly Version: 2023.1.0.0
    Win32 Version: 2023.1.0.0
    CodeBase: file:///E:/Projects/FastReport.Community.2023.1.0/Designer.exe

FastReport.Data.SQLite
    Assembly Version: 2023.1.0.0
    Win32 Version: 2023.1.0.0
    CodeBase: file:///E:/Projects/FastReport.Community.2023.1.0/Designer.exe

FastReport.DataVisualization
    Assembly Version: 2022.3.2.0
    Win32 Version: 2023.1.0.0
    CodeBase: file:///E:/Projects/FastReport.Community.2023.1.0/Designer.exe

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll

System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll

System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll

System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
```

**Screenshots**
![image](https://user-images.githubusercontent.com/84759/215248194-d5307e5f-95a4-4590-bc97-2f52fb220b88.png)

**Device (please complete the following information):**
 - OS: Win 11 64b
 - Version Designer CE 2023.1.0

**Additional context**

**Comment by Yamasiash** [comment]
Hello!

We have not been able to reproduce this problem. Could you please attach your database file on which we can reproduce the problem?

**Comment by MaratAlaev** [comment]
Hello!

The problem is most likely related to 
that there was a bug earlier with the connection of procedures with the parameter 

Now this problem has been fixed

Best regards 
Marat
