### ISSUE TITLE
Out of memory error when instanciateing PDFSimpleExport

### ISSUE THREAD

**Issue by jtenganForte** [FastReports/FastReport#553]
Error occurs on this line of code:

PDFSimpleExport pdfExport = new PDFSimpleExport();

Anyone have any ideas what we should look into? It is happening on one server but not another one with a copy of the same database. 

Thanks

Stack trace:
at System.Drawing.Graphics.Save()
   at FastReport.GdiGraphics.Save()
   at FastReport.TextObject.CalcSize()
   at FastReport.TextObject.CalcHeight()
   at FastReport.BandBase.CalcHeight()
   at FastReport.Engine.ReportEngine.PrepareBand(BandBase band, Boolean getData)
   at FastReport.Engine.ReportEngine.ShowBandToPreparedPages(BandBase band, Boolean getData)
   at FastReport.Engine.ReportEngine.ShowBand(BandBase band, Boolean getData)
   at FastReport.Engine.ReportEngine.ShowBand(BandBase band)
   at FastReport.Engine.ReportEngine.RunDataBand(DataBand dataBand, Int32 rowCount, Boolean keepFirstRow, Boolean keepLastRow)
   at FastReport.Engine.ReportEngine.RunDataBand(DataBand dataBand)
   at FastReport.Engine.ReportEngine.RunBands(BandCollection bands)
   at FastReport.Engine.ReportEngine.RunReportPage(ReportPage page)
   at FastReport.Engine.ReportEngine.RunReportPages()
   at FastReport.Engine.ReportEngine.RunReportPages(ReportPage page)
   at FastReport.Engine.ReportEngine.Run(Boolean runDialogs, Boolean append, Boolean resetDataState, ReportPage page)
   at FastReport.Engine.ReportEngine.Run(Boolean runDialogs, Boolean append, Boolean resetDataState)
   at FastReport.Report.Prepare(Boolean append)
   at FastReport.Report.Prepare()
   at Forte.ChiroCloud.Business.ERAMessageBL.GeneratePDFForSummaryReport(List`1 data, String FileNameWithPath) in /root/ChiroCloud/Forte.ChiroCloud.Business/ERA/ERAMessageBL.cs:line 272
   at Forte.ChiroCloud.Business.ERAMessageBL.ConvertClaimsToSummaryPDFReport(List`1 m_Claims, Int32 days, String unique_id, String config_fileUploadLocation) in /root/ChiroCloud/Forte.ChiroCloud.Business/ERA/ERAMessageBL.cs:line 248
   at Forte.ChiroCloud.Business.ERAMessageBL.HandleLevelTwoAckReports(List`1 ackReportLoadIds, ServiceClientClass& scOptum, OptumXmlReportHelperClass& scHelper, Int32 days, String config_fileUploadLocation) in /root/ChiroCloud/Forte.ChiroCloud.Business/ERA/ERAMessageBL.cs:line 201
   at Forte.ChiroCloud.Business.ERAMessageBL.RetrieveMessages(Int32 days, Boolean unread, String config_fileUploadLocation) in /root/ChiroCloud/Forte.ChiroCloud.Business/ERA/ERAMessageBL.cs:line 102
   at Forte.ChiroCloud.Api.Controllers.EraController.RetrieveMessages(Int32 days, Boolean unread) in /root/ChiroCloud/Forte.ChiroCloud.Api/Controllers/EraController.cs:line 318
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()

**Comment by BogdanStegachev** [comment]
Hello!

The new version of FastReport.Community does not reproduce this problem

Best regards,
Bogdan
