### ISSUE TITLE
Community designer crashes on opening

### ISSUE THREAD

**Issue by fernandocristan** [FastReports/FastReport#597]
**Describe the bug**
FastReport.Community.2023.2.0 crashes when opening.

When i downloaded first time, i used normally, then in another day starts to crashes when opening

**Stacktrace**
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.OverflowException: Overflow error.
   at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.FillRectangle(Brush brush, Single x, Single y, Single width, Single height)
   at FastReport.BandBase.Draw(FRPaintEventArgs e)
   at FastReport.Design.PageDesigners.Page.ReportWorkspace.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4614.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Designer
    Assembly Version: 2023.2.0.0
    Win32 Version: 2023.2.0.0
    CodeBase: file:///E:/FastReport.Community.2023.2.0/Designer.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
FastReport
    Assembly Version: 2023.2.0.0
    Win32 Version: 2023.2.0.0
    CodeBase: file:///E:/FastReport.Community.2023.2.0/Designer.exe
----------------------------------------
FastReport.Bars
    Assembly Version: 2023.2.0.0
    Win32 Version: 2023.2.0.0
    CodeBase: file:///E:/FastReport.Community.2023.2.0/Designer.exe
----------------------------------------
FastReport.Editor
    Assembly Version: 2023.2.0.0
    Win32 Version: 2023.2.0.0
    CodeBase: file:///E:/FastReport.Community.2023.2.0/Designer.exe
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
FastReport.Compat
    Assembly Version: 2023.1.8.0
    Win32 Version: 2023.1.8.0
    CodeBase: file:///E:/FastReport.Community.2023.2.0/FastReport.Compat.DLL
----------------------------------------
FastReport.DataVisualization
    Assembly Version: 2022.3.2.0
    Win32 Version: 2022.3.2.0
    CodeBase: file:///E:/FastReport.Community.2023.2.0/FastReport.DataVisualization.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4584.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
FastReport.Data.Couchbase
    Assembly Version: 2023.2.0.0
    Win32 Version: 2023.2.0.0
    CodeBase: file:///E:/FastReport.Community.2023.2.0/Designer.exe
----------------------------------------
FastReport.Data.Json
    Assembly Version: 2023.2.0.0
    Win32 Version: 2023.2.0.0
    CodeBase: file:///E:/FastReport.Community.2023.2.0/FastReport.Data.Json.DLL
----------------------------------------
FastReport.Data.Json
    Assembly Version: 2023.2.0.0
    Win32 Version: 2023.2.0.0
    CodeBase: file:///E:/FastReport.Community.2023.2.0/Designer.exe
----------------------------------------
Newtonsoft.Json
    Assembly Version: 11.0.0.0
    Win32 Version: 11.0.2.21924
    CodeBase: file:///E:/FastReport.Community.2023.2.0/Newtonsoft.Json.DLL
----------------------------------------
FastReport.Data.MongoDB
    Assembly Version: 2023.2.0.0
    Win32 Version: 2023.2.0.0
    CodeBase: file:///E:/FastReport.Community.2023.2.0/Designer.exe
----------------------------------------
FastReport.Data.MySql
    Assembly Version: 2023.2.0.0
    Win32 Version: 2023.2.0.0
    CodeBase: file:///E:/FastReport.Community.2023.2.0/Designer.exe
----------------------------------------
FastReport.Data.OracleODPCore
    Assembly Version: 2023.2.0.0
    Win32 Version: 2023.2.0.0
    CodeBase: file:///E:/FastReport.Community.2023.2.0/Designer.exe
----------------------------------------
FastReport.Data.Postgres
    Assembly Version: 2023.2.0.0
    Win32 Version: 2023.2.0.0
    CodeBase: file:///E:/FastReport.Community.2023.2.0/Designer.exe
----------------------------------------
FastReport.Data.SQLite
    Assembly Version: 2023.2.0.0
    Win32 Version: 2023.2.0.0
    CodeBase: file:///E:/FastReport.Community.2023.2.0/Designer.exe
----------------------------------------
FastReport.DataVisualization
    Assembly Version: 2022.3.2.0
    Win32 Version: 2023.2.0.0
    CodeBase: file:///E:/FastReport.Community.2023.2.0/Designer.exe
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.
```

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Screenshots**
![image](https://github.com/FastReports/FastReport/assets/32015491/0560005b-4b7e-4330-b61f-5d42192e0880)

**Device (please complete the following information):**
 - OS: windows 10 Pro
 - Version: 21H2 - 19044.2846

**Comment by fernandocristan** [comment]
When i deleted FastReport.Community.config, it works again

**Comment by BogdanStegachev** [comment]
Hello!

We are also looking forward to your feedback on FastReport.OpenSource 2023.3.0 version

Best regards,
Bogdan

**Comment by fernandocristan** [comment]
Apparently, it's working. In case it crashes again, i will be in touch. Thanks.
